version: '3.8'

services:
  banking-assistant:
    image: ${ACR_LOGIN_SERVER}/banking-assistant:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "-e", "import('http').then(http => { const req = http.get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }); req.on('error', () => process.exit(1)); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  banking-brokerage:
    image: ${ACR_LOGIN_SERVER}/banking-brokerage:latest
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "-e", "import('http').then(http => { const req = http.get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }); req.on('error', () => process.exit(1)); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: banking-mock-production
